Feat: Skeleton, Schemas, createUser usecase, postUser route
Photoapp-Team/PHOTOAPP_MVP_BACKEND pull request #1
Opened 2022-10-01 03:21 UTC by deathmarcus

Feat: Skeleton (index.js, server,js, package-json)
Feat: Schemas (packages, photos, sessions, users)
Feat: user usecase > createUser
Feat: user route > post

2022-10-01 03:47 UTC, alepaez-dev requested changes
Suoper buen trabajo

2022-10-01 03:47 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  finalPics: {
Better name

2022-10-01 03:49 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  finalPics: {
esto es un ejemplo para todos de como se comenta un pull request

2022-10-01 04:42 UTC, GiovanniGlez approved these changes
Great job, super understandable and very fluid everything

2022-10-03 16:09 UTC, alepaez-dev approved these changes
Para una v1 y que se pongan a trabajar en los endpoints esta super bien excelente trabnajo


Cuando empiece el flujo principal, hacemos una v2 mucho mas completa

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/photos.model.js
> +  info: {
Pregunta, por que todo dentro de info ?. Siempre sera photos.info ???

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/photos.model.js
> +              type: String,
Que es tipo de likes ?. Hay diferentes tipos de likes?. Aparte como sabes quien dio el like, cuando un usuario entra como sabe que ya le dio like a una foto.
```suggestion
              userId: String,  
```

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/photos.model.js
> +          type: String,
Me hace sentido que las fotos tengan ubicaciones. Pero guardar todo en un string esta complicado. Mas si quieres filtrar despues. (esto va para cualquier tipo de location en cualquier model.
```suggestion
          type: {
             city: String,
             state: String,
             country: String,
             zipcode: String,
          },
          
```

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  userId: {
Creo que ya te habia preguntado esto pero ya se me olvido :octocat: . Una session es para un usuario nada mas o pueden ser mas ?. Misma pregunta para fotografos

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/sessions.model.js
> +        isChecked: {
que es isChecked ?

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/sessions.model.js
> +        comment: {
que es comment ?. Se pueden comentar las pics?. Seria comments y un arreglo entonces, y esto se tiene que pensar bien.

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  downloadLink: {
este te lo podrias ahorrar si ya tienes la url donde esta la imagen arriba(aws s3) y descargarla desde el frontend. O como lo tienes pensado hacer ?

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +    required: true,
Necesita un regex, literal puedo ingresar alejandra.hola y me lo va a aceptar.

```suggestion
    required: true,
    match: /^.*@.*\..*$/,
```

O, si quieres otro: https://ihateregex.io/

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +        type: String,
```suggestion
        userId: String,

```

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +    type: [
```suggestion
    type: [String]

```

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +  notifications: {
Para que el numero de notificationes ? Esto es nice to have o que onda

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +        type: String,
Lo mismo que arriba.

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +        type: String,
Esto lo dejamos asi por el momento

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +  premium: {
esto se puede cambiar a algo tipo licenses, o subscriptions. Que pasa si en un futuro tienes mas aparte de premium. Tambien por el momento esta bien asi.

2022-10-03 16:09 UTC, alepaez-dev commented on src/routes/user.route.js
> +    console.log(body);
```suggestion


```

2022-10-03 16:09 UTC, alepaez-dev commented on src/routes/user.route.js
> +    response.status(400);
```suggestion
    response.status(error.status || 400);

```

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  userId: {
Estoe s importante

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +    minlenght: 3,
```suggestion
    minlength: 3,

```

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +    minlenght: 3,
Lo mismo para todos los typos

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/users.model.js
> +        type: Number,
Yo vivo en el E1203 por ejemplo
```suggestion
        type: String,

```

2022-10-03 16:09 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  status: {
Un enum estaria bien

2022-10-03 16:11 UTC, alepaez-dev approved these changes

2022-10-03 16:19 UTC, alfredopizana commented on src/models/sessions.model.js
> +  userId: {
Chequen la documentacion del populate, si el objetivo es traer la informacion relacionada agreguen el tipo adecuado, les va a ahorar tiempo 

`{ type: Schema.Types.ObjectId, ref: 'Person' }`
https://mongoosejs.com/docs/populate.html#populate

De mongoose:

> **Note**: ObjectId, Number, String, and Buffer are valid for use as refs. However, you should use **ObjectId** unless you are an advanced user and have a good reason for doing so.

2022-10-03 18:49 UTC, deathmarcus commented on src/models/photos.model.js
> +  info: {
Si, no lo había notado, normalmente eso me falla hasta que hago la primer prueba y ya veo el documento en la bd, entonces ya hago las correcciones. Lo cambio.

2022-10-03 19:39 UTC, deathmarcus commented on src/models/photos.model.js
> +              type: String,
No, sólo es uno jeje. Ya lo modifiqué

2022-10-03 19:40 UTC, deathmarcus commented on src/models/photos.model.js
> +          type: String,
Tienes razón, cuando estaba haciendo el schema vi que lo necesitabamos pero ya no lo desarrollé bien. Ya lo cambié

2022-10-03 19:51 UTC, deathmarcus commented on src/models/sessions.model.js
> +  userId: {
@alepaez-dev 
Hay casos donde puede haber más de un cliente, como graduaciones, sesiones conjuntas, etc. Y también puede haber más de un fotógrafo por sesión, supongo que puede ser en el caso de sesiones de cursos de foto, o cuando hay agencias de foto y mandan a varios, pero seguramente se puede dar el caso. Por eso lo definí como un array, pero no estoy seguro si sea el approach correcto. También en el modelo de users agregué un nuevo rol, el de "enterprise" justo para ese tipo de casos y porque tienen ciertas características que los distinguen.

@alfredopizana 
Si, justo estuve buscando como declarar ese tipo de Objeto, pero no lo pude encontrar, por eso lo había dejado como String por el momento, ahorita modifico los que sean necesarios. Pero tengo una pregunta, según lo que entendí el populate sirve para llenar el campo o los campos de una colección con info de otra colección. Pero lo que no pude encontrar es como vincular o relacionar campos dentro del mismo Schema, por ejemplo en este caso dependiendo del rol, un tipo de usuario tiene ciertos campos exclusivos. ¿Esto se puede hacer dentro del Schema o esa lógica se tiene que hacer en otro lugar?

2022-10-03 19:52 UTC, deathmarcus commented on src/models/sessions.model.js
> +        isChecked: {
Que si fue seleccionada o palomeada para que se mande a la edición final.

2022-10-03 19:55 UTC, deathmarcus commented on src/models/sessions.model.js
> +        comment: {
Si, se pensó y se añadió por si el cliente quiere hacer una petición especial al fotógrafo en la edición de alguna foto que seleccionaron durante el preview de la sesión. No tanto como que se pueda comentar cualquier foto en la plataforma

2022-10-03 19:59 UTC, deathmarcus commented on src/models/sessions.model.js
> +  downloadLink: {
Pensamos que para facilitar la entrega de las fotos editadas es necesario que se genere un link de descarga para el cliente, que contenga un archivo con todas las fotos finales.

2022-10-03 20:00 UTC, deathmarcus commented on src/models/users.model.js
> +    required: true,
Si, de acuerdo, añado uno.

2022-10-03 20:06 UTC, deathmarcus commented on src/models/users.model.js
> +    minlenght: 3,
La dislexia. Corregido

2022-10-03 20:10 UTC, deathmarcus commented on src/models/sessions.model.js
> +  status: {
Pero el paquete depende del modelo de paquetes, aquí más bien sería referenciarlo a esa colección no?

2022-10-03 20:16 UTC, deathmarcus commented on src/models/users.model.js
> +  premium: {
Si, todavía tengo dudas de cómo manejarlo.

2022-10-03 20:17 UTC, deathmarcus commented on src/models/users.model.js
> +        type: String,
Cambiado

2022-10-03 20:17 UTC, deathmarcus commented on src/models/users.model.js
> +        type: String,
Ok

2022-10-03 20:18 UTC, deathmarcus commented on src/models/users.model.js
> +  notifications: {
Si, por el momento es nice to have, todavía no sabemos cómo lo vamos a manejar, pero se incluyó por si en algún momento se usa.

2022-10-03 20:18 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  status: {
Me refiero al status

2022-10-03 20:21 UTC, alepaez-dev commented on src/models/sessions.model.js
> +        isChecked: {
Por quién? Múltiples clientes?. Si quieres estás cosas ya las hablamos en nuestra junta el miércoles o como gustes

2022-10-03 20:21 UTC, deathmarcus commented on src/models/sessions.model.js
> +  status: {
Ahh si, ahorita lo agrego

2022-10-03 20:23 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  userId: {
Creo que aquí el flujo llega a cambiar un poco y se tiene que considerar bien, apenas que ya lo hayan considerado y ya esté listo. Porque que pasa con los pagos cuando son muchos fotógrafos, etc, son preguntas que se me vienen y se les van a venir a los jueces. Lo platicamos

2022-10-03 20:35 UTC, alepaez-dev commented on src/models/sessions.model.js
> +        comment: {
Y esto es por sesión?. Entonces en la ux/xi se va a reflejar en la sesión completa con todas las fotos sin indicar en qué foto en especial se necesita el pedido especial del cliente vd.
Se podría llamar notes.

Por ejemplo, Uber eats hay ciertos platillos(no todos) dónde te permite agregar nota por platillo de que quiero capsut etc, y aparte en el pedido en general es otra nota.

Lo recomiendo así como traes para no complicarnos tanto, pero de que se puede se puede, más en bases de datos no relacionales cómo mongo está simple. Pongo todo esto aquí porque se me olvida pa platicarlo el miércoles con todes

2022-10-03 20:36 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  downloadLink: {
Muy bien

2022-10-06 01:10 UTC, alepaez-dev approved these changes

2022-10-06 01:10 UTC, alepaez-dev commented on src/models/sessions.model.js
> +  userId: {
Creo que esto esta resuelto con la junta de hace ratito. Me imagino que vamos a limitar por fotografo y por cliente y dejarlo como nice to have.

2022-10-06 01:10 UTC, alepaez-dev commented on src/models/sessions.model.js
> +        isChecked: {
Resuelto

2022-10-12 22:00 UTC, merged