created stripe implementation
Photoapp-Team/PHOTOAPP_MVP_BACKEND pull request #11
Opened 2022-10-20 03:32 UTC by AraceliRomero

cree la implementación básica del stripe, hace falta guardar información básica del usuario se va a hacer en la segunda integración

2022-10-21 08:27 UTC, deathmarcus approved these changes
Se ve muy bien!

2022-10-22 03:39 UTC, luised2301 approved these changes

2022-10-28 14:51 UTC, alepaez-dev requested changes

2022-10-28 14:51 UTC, alepaez-dev commented on package.json
> -    "stripe": "^10.14.0"
Como decia @alfredopizana quitas el paquete de stripe y va a tronar

Cuidado con esto @deathmarcus @luised2301

2022-10-28 21:23 UTC, alfredopizana commented on src/middlewares/auth.middleware.js
> +const paymentes = require("dotenv").config()
No se esta usando

2022-11-03 21:27 UTC, alfredopizana approved these changes

2022-11-03 21:29 UTC, deathmarcus approved these changes
Ok

2022-11-04 05:18 UTC, alepaez-dev approved these changes

2022-11-04 05:43 UTC, merged