Develop auth
Photoapp-Team/PHOTOAPP_MVP_BACKEND pull request #3
Opened 2022-10-13 21:52 UTC by luised2301

user CRUD completed, Auth created, login created

2022-10-13 23:32 UTC, alepaez-dev requested changes
Mas que nada lo del status de 201.

2022-10-13 23:32 UTC, alepaez-dev commented on src/middlewares/auth.middleware.js
> +    const verifiedToken = jwt.verify(token);
la constante verifiedToken es utilizada?. Si no es asi, la puedes ahorrar, con utilizar el .verify de permite o te lanza errores si el token es correcto 
```suggestion
    jwt.verify(token);

```

2022-10-13 23:32 UTC, alepaez-dev commented on src/routes/user.route.js
> +    response.status(201);
No es el status correcto para un get.

https://httpstatusdogs.com/

2022-10-13 23:32 UTC, alepaez-dev commented on src/routes/user.route.js
>        data: {
Un poco redundate lo de userETC. Si no quieres un nesting mas puedes hacer:  
```suggestion
      data: user

```

2022-10-14 02:18 UTC, luised2301 commented on src/middlewares/auth.middleware.js
> +    const verifiedToken = jwt.verify(token);
de acuerdo con esta, no se esta usando

2022-10-14 02:18 UTC, luised2301 commented on src/routes/user.route.js
> +    response.status(201);
lo corrijo

2022-10-14 14:56 UTC, luised2301 commented on src/routes/user.route.js
>        data: {
esta esta buena pero quería antes revisar si a futuro decidimos mandar solo alguna información del  user, porque si lo mandamos completo viene hasta la contraseña hasheada.

2022-10-14 16:28 UTC, luised2301 commented on src/routes/user.route.js
> +    response.status(201);
seria un 200 ? (ok)

2022-10-14 16:43 UTC, alepaez-dev commented on src/routes/user.route.js
> +    response.status(201);
yes, como es por default hasta puedes quitar el response.status

2022-10-14 16:46 UTC, alepaez-dev commented on src/routes/user.route.js
>        data: {
Ah si, la contraseña no se manda. Wachate estos 2 approach entons, obviamente con lo que quieras regresar, yo nomas puse nomnbre y email.
1 approach :
```suggestion
      const { email, name } = user 
      data: {
           email,
           name
      }
```
En Javascript si la propiedad de un objeto y la variable que contiene su valor se llaman igual, solo se pone una vez.

2 approach:
Excluir pass
https://mongoosejs.com/docs/api.html#query_Query-select
![Screen Shot 2022-10-14 at 11 50 22](https://user-images.githubusercontent.com/74441510/195900154-95ad7267-8f9d-4266-aa97-e54cfec7aec9.png)

El chiste era omitir el userAlgo :)

2022-10-14 16:48 UTC, alepaez-dev commented on src/routes/user.route.js
> +    response.status(201);
Puedes commitear esto 
```suggestion


```

2022-10-14 16:52 UTC, alepaez-dev reviewed
cambios sugeridos

2022-10-14 17:04 UTC, luised2301 commented on src/routes/user.route.js
>        data: {
yo se pero lo queria dejar como placeholder en lo que vamos resolviendo la logica y ya despues mandar solo lo que necesitamos, o asi lo pensaba

2022-10-14 19:18 UTC, alepaez-dev approved these changes

2022-10-14 22:02 UTC, deathmarcus approved these changes
De lujo!

2022-10-15 01:10 UTC, merged